sudo: required
services:
    - docker
addons:
    ssh_known_hosts:
        - $DROPLET_IP
env:
    global:
        - SHA=$(git rev-parse HEAD)
branches:
    only:
        - master
        - staging
before_install:
    - openssl aes-256-cbc -K $encrypted_bacf9fc6807e_key -iv $encrypted_bacf9fc6807e_iv -in travis_rsa.enc -out travis_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ./travis_rsa
    - echo -e "Host $DROPLET_IP\nStrictHostKeyChecking no\n" >> ~/.ssh/config
    - ssh-add ./travis_rsa
    # Build client test build
    - docker build -t alexgreff/personal-website-client-test -f ./client/Dockerfile.dev ./client
script:
    # Run client test script
    - docker run alexgreff/personal-website-client-test npm run test:coverage
after_success:
    # Build docker images
    - docker build -t alexgreff/personal-website-client:latest -t alexgreff/personal-website-client:$SHA -f ./client/Dockerfile ./client
    - docker build -t alexgreff/personal-website-server:latest -t alexgreff/personal-website-server:$SHA -f ./server/Dockerfile ./server
    - docker build -t alexgreff/personal-website-nginx:latest -t alexgreff/personal-website-nginx:$SHA -f ./nginx/Dockerfile ./nginx
    # Login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the images
    - docker push alexgreff/personal-website-client:latest
    - docker push alexgreff/personal-website-server:latest
    - docker push alexgreff/personal-website-nginx:latest
    - docker push alexgreff/personal-website-client:$SHA
    - docker push alexgreff/personal-website-server:$SHA
    - docker push alexgreff/personal-website-nginx:$SHA
after_script:
    # Send the docker-compose.yml file over
    - scp -i ./travis_rsa ./docker-compose.yml travis@$DROPLET_IP:/var/app/docker-compose.yml

    # Send the deploy.sh file over
    - scp -i ./travis_rsa ./deploy.sh travis@$DROPLET_IP:/var/app/deploy.sh

    # Ssh in to droplet, export the prod env vars and run the deploy.sh script
    - ssh -i ./travis_rsa travis@$DROPLET_IP 
        'export TRAVIS_USER_PASSWORD='$TRAVIS_USER_PASSWORD'; 
        export SHA='$SHA';
        export PERSONAL_WEBSITE_MONGO_URI='$PERSONAL_WEBSITE_MONGO_URI';
        export PERSONAL_WEBSITE_MONGO_USERNAME='$PERSONAL_WEBSITE_MONGO_USERNAME'; 
        export PERSONAL_WEBSITE_MONGO_PASSWORD='$PERSONAL_WEBSITE_MONGO_PASSWORD';
        export PERSONAL_WEBSITE_JWT_SECRET='$PERSONAL_WEBSITE_JWT_SECRET';
        export PERSONAL_WEBSITE_JWT_TOKEN_EXPIRE_TIME='$PERSONAL_WEBSITE_JWT_TOKEN_EXPIRE_TIME';
        cd /var/app; bash ./deploy.sh'