sudo: required
services:
    - docker

before_install:
    - docker build -t alexgreff/personal-website-client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run alexgreff/personal-website-client-test npm run test:coverage

after_success:
    - docker build -t alexgreff/personal-website-client ./client
    - docker build -t alexgreff/personal-website-server ./server
    - docker build -t alexgreff/personal-website-nginx ./nginx
    # Log into the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push built images onto docker hub
    - docker push alexgreff/personal-website-client
    - docker push alexgreff/personal-website-server
    - docker push alexgreff/personal-website-nginx

# deploy:
#     provider: script
#     script: bash deploy.sh
#     on:
#         branch: master