# Sets up the development environment but with the client production image running
version: "3.2"
services: 
    client:
        build: 
            dockerfile: Dockerfile
            context: ./client
        ports: 
            - "3050:8080"
        container_name: personal_website_client
        volumes: 
            - ./client:/app