# Sets up the production environment
version: "3.2"
services: 
    nginx:
        restart: always
        image: alexgreff/personal-website-nginx:${SHA}
        ports:
            - "80:80"
        networks:
            - personal-website
    api:
        image: alexgreff/personal-website-server:${SHA}
        environment: 
            - "MONGO_URI=${PERSONAL_WEBSITE_MONGO_URI}"
            - "MONGO_USERNAME=${PERSONAL_WEBSITE_MONGO_USERNAME}"
            - "MONGO_PASSWORD=${PERSONAL_WEBSITE_MONGO_PASSWORD}"
            - "JWT_KEY=${PERSONAL_WEBSITE_MONGO_PASSWORD}"
            - "JWT_TOKEN_EXPIRE_TIME=${PERSONAL_WEBSITE_JWT_TOKEN_EXPIRE_TIME}"
        networks:
            - personal-website
    client:
        image: alexgreff/personal-website-client:${SHA}
        networks:
            - personal-website
networks:
    personal-website: