# Sets up the development environment
version: "3.2"
services: 
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3050:80"
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment: 
            - "MONGO_URI=${PERSONAL_WEBSITE_MONGO_URI}"
            - "MONGO_USERNAME=${PERSONAL_WEBSITE_MONGO_USERNAME}"
            - "MONGO_PASSWORD=${PERSONAL_WEBSITE_MONGO_PASSWORD}"
            - "JWT_KEY=${PERSONAL_WEBSITE_JWT_SECRET}"
            - "JWT_TOKEN_EXPIRE_TIME=${PERSONAL_WEBSITE_JWT_TOKEN_EXPIRE_TIME}"
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true