# Sets up the production environment
version: "3.2"
services: 
    nginx:
        restart: always
        image: alexgreff/personal-website-nginx:${SHA}
        volumes: 
            # Connect nginx with certbot
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - "80:80" # Http traffic
            - "443:443" # LetsEncrypt traffic
        # Renew the newly obtained HTTPS certificates
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
            - personal-website
    api:
        image: alexgreff/personal-website-server:${SHA}
        environment: 
            - "MONGO_URI=${PERSONAL_WEBSITE_MONGO_URI}"
            - "MONGO_USERNAME=${PERSONAL_WEBSITE_MONGO_USERNAME}"
            - "MONGO_PASSWORD=${PERSONAL_WEBSITE_MONGO_PASSWORD}"
            - "JWT_KEY=${PERSONAL_WEBSITE_JWT_SECRET}"
            - "JWT_TOKEN_EXPIRE_TIME=${PERSONAL_WEBSITE_JWT_TOKEN_EXPIRE_TIME}"
            - "PERSONAL_WEBSITE_CONTACT_EMAIL_SERVICE=${PERSONAL_WEBSITE_CONTACT_EMAIL_SERVICE}"
            - "PERSONAL_WEBSITE_CONTACT_EMAIL=${PERSONAL_WEBSITE_CONTACT_EMAIL}"
            - "PERSONAL_WEBSITE_CONTACT_PASSWORD=${PERSONAL_WEBSITE_CONTACT_PASSWORD}"
        # volumes:
        #     - /var/app/uploads:/app/uploads
        networks:
            - personal-website
    client:
        image: alexgreff/personal-website-client:${SHA}
        networks:
            - personal-website
    certbot:
        image: certbot/certbot
        # Connect with nginx
        volumes: 
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        networks:
            - personal-website
        # Renew the certificate every 12 hours
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
    personal-website: