export default {
    "github": "brands/github",
    "linkedin": "brands/linkedin",
    "email": "envelope",
    "soundcloud": "brands/soundcloud",
    "website": "external-link-alt",
    "facebook": "brands/facebook",
    "instagram": "brands/instagram",
    "pinterest": "brands/pinterest",
    "snapchat": "brands/snapchat",
    "youtube": "brands/youtube",
    "vimeo": "brands/vimeo-v",
    "docker": "brands/docker",
    "twitter": "brands/twitter",
    "default": "link",
};