// AutoTheme store
export const IS_AUTO_THEME_ENABLED = "IS_AUTO_THEME_ENABLED";
export const GET_CURRENT_THEME_NAMESPACE = "GET_CURRENT_THEME_NAMESPACE";
export const GET_CURRENT_AUTO_THEME_NAMESPACE = "GET_CURRENT_AUTO_THEME_NAMESPACE";
export const GET_CURRENT_STATIC_THEME_NAMESPACE = "GET_CURRENT_STATIC_THEME_NAMESPACE";

// Project store
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";

// Theme store
export const GET_ALL_THEMES = "GET_ALL_THEMES";
export const GET_THEME = "GET_THEME";
export const GET_ALL_NAMESPACES = "GET_ALL_NAMESPACES";
export const GET_NAMESPACE = "GET_NAMESPACE";