// AutoTheme store
export const SET_AUTO_THEME_ENABLED = "SET_AUTO_THEME_ENABLED";
export const SET_CURRENT_AUTO_THEME_NAMESPACE = "SET_CURRENT_AUTO_THEME_NAMESPACE";
export const SET_CURRENT_STATIC_THEME_NAMESPACE = "SET_CURRENT_STATIC_THEME_NAMESPACE";

// Project store
export const POPULATE_PROJECTS = "POPULATE_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";

// Experience store
export const POPULATE_EXPERIENCE = "POPULATE_EXPERIENCE";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const REMOVE_EXPERIENCE = "REMOVE_EXPERIENCE";
export const EDIT_EXPERIENCE = "EDIT_EXPERIENCE";

// Theme store
export const ADD_THEME = "ADD_THEME";
export const REMOVE_THEME = "REMOVE_THEME";
export const EDIT_THEME = "EDIT_THEME";
export const ADD_NAMESPACE = "ADD_NAMESPACE";
export const REMOVE_NAMESPACE = "REMOVE_NAMESPACE";
export const EDIT_NAMESPACE = "EDIT_NAMESPACE";