FROM node:alpine

WORKDIR /app
COPY ./package.json ./

RUN apk add --no-cache make gcc g++ python

# RUN npm config set puppeteer_download_host=https://npm.taobao.org/mirrors # Download chromium with mirror
RUN npm install

COPY . .

CMD ["npm", "run", "start:dev"]